sudo: required

dist: bionic
language: c
cache: false

#env:
#    matrix:
#      - TARGET=test
#      - OS=ubuntu DIST=xenial
#      - OS=ubuntu DIST=bionic
#      - OS=ubuntu DIST=disco

before_install:
  - sudo apt-get install -y python3-dev  libssl-dev openssl libengine-gost-openssl1.1 

addons:
  apt:
    update: true

script:
  - git describe --long
  - python3 setup.py build
  - python3 setup.py install
  - python3 pycms_test.py


notifications:
  email:
    recipients:
      - dmitry.dulesov@gmail.com
    on_success: change
    on_failure: always