sudo: required

dist: bionic
language: python
cache: false

#env:
#    matrix:
#      - TARGET=test
#      - OS=ubuntu DIST=xenial
#      - OS=ubuntu DIST=bionic
#      - OS=ubuntu DIST=disco

before_install:
  - sudo apt-get install -y libssl-dev openssl libengine-gost-openssl1.1 

matrix:
  include:
  - python: "3.6"
  - python: "3.7"


addons:
  apt:
    update: true

script:
  - git describe --tags
  - python setup.py build
  - python setup.py install
  - python pycms_test.py


notifications:
  email:
    recipients:
      - dmitry.dulesov@gmail.com
    on_success: change
    on_failure: always